name = 'harmony'
compatibility_date = '2024-04-09'
pages_build_output_dir = "./dist"

[vars]
VITE_DEV_URL = 'http://localhost:5173'
DEV = true
PROD = false

[env.preview.vars]
DEV = false

[env.production.vars]
PROD = true
DEV = false
